### ISSUE TITLE
Plugin is not listed in available plugins 

### ISSUE THREAD

**Issue by ecararus** [aiven/http-connector-for-apache-kafka#126]
I'm using Kafka 2.4.0
Copied http-connector-for-apache-kafka-0.6.0.jar in the folder mentioned in plugin.path= in connect-distributed.properties
After restart in the logs i see the plugins being scanned :

`[2022-09-21 13:42:06,711] INFO Loading plugin from: /opt/plugins/http-connector-for-apache-kafka (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:241)
[2022-09-21 13:42:06,716] DEBUG Loading plugin urls: [file:/opt/plugins/http-connector-for-apache-kafka/http-connector-for-apache-kafka-0.6.0-SNAPSHOT.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-annotations-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-core-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-databind-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/slf4j-api-1.7.36.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:248)
[2022-09-21 13:42:07,008] DEBUG Skipping class org.apache.kafka.connect.sink.SinkConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:352)
[2022-09-21 13:42:07,025] INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/plugins/http-connector-for-apache-kafka/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:264)
`

When i call REST endpoint i can't see the HttpSinkConnector
`curl --location --request GET 'localhost:8083/connector-plugins/'`

Similar when i try to create connector using API:
`
curl --location --request PUT 'localhost:8083/connector-plugins/HttpSinkConnector/config/validate' \
--header 'Content-Type: application/json' \
--data-raw '{
    "connector.class": "io.aiven.kafka.connect.http.HttpSinkConnector",
    "name": "test-http-sink",

    "topics.regex": "test.*",
    
    "http.authorization.type": "none",
    "http.url": "http://loclhost:8121",
    
    "batching.enabled": true,
    "batch.max.size": 2,
    "tasks.max": "1",
    
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter"
}'

`

I'm  getting:
`{
    "error_code": 500,
    "message": "Failed to find any class that implements Connector and which name matches io.aiven.kafka.connect.http.HttpSinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.4.0', encodedVersion=2.4.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.4.0', encodedVersion=2.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.4.0', encodedVersion=2.4.0, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.4.0', encodedVersion=2.4.0, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.4.0', encodedVersion=2.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.4.0', encodedVersion=2.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.4.0', encodedVersion=2.4.0, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.4.0', encodedVersion=2.4.0, type=source, typeName='source', location='classpath'}"
}`

Similar issue has been described here: https://stackoverflow.com/questions/68440097/open-source-alternative-for-kafka-confluent-http-sink-connector.

Just as headsup i have tested with version 0.5.0 and 0.7.0-Snapshot similar behaviour.

**Comment by ivanyu** [comment]
Hi @ecararus 
Thank you for reporting this.
That's rather strange, I tried running it with the Connect worker using 2.4, it worked just fine. I assume you're using the distributed mode. Could you please try the standalone more? Also, could you please share the output of `tree <plugin.path value>`?

**Comment by ecararus** [comment]
Hello @ivanyu 
Sorry, forgot to mention that indeed im using in distributed mode.

in the config i have:
`plugin.path=/opt/plugins,/usr/local/java`

The tree: 
`

/opt/plugins
└── http-connector-for-apache-kafka
   ├── http-connector-for-apache-kafka-0.6.0.jar
   ├── jackson-annotations-2.13.2.jar
   ├── jackson-core-2.13.2.jar
   ├── jackson-databind-2.13.2.jar
   └── slf4j-api-1.7.36.jar

`

When i started in standalone im getting :

`[2022-09-21 15:47:54,921] INFO Scanning for plugin classes. This might take a moment ... (org.apache.kafka.connect.cli.ConnectStandalone:78)
[2022-09-21 15:47:54,956] INFO Loading plugin from: /opt/plugins/http-connector-for-apache-kafka (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:241)
[2022-09-21 15:47:54,959] DEBUG Loading plugin urls: [file:/opt/plugins/http-connector-for-apache-kafka/http-connector-for-apache-kafka-0.6.0.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-annotations-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-core-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/jackson-databind-2.13.2.jar, file:/opt/plugins/http-connector-for-apache-kafka/slf4j-api-1.7.36.jar] (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:248)
[2022-09-21 15:47:55,216] DEBUG Skipping class org.apache.kafka.connect.sink.SinkConnector as it is not concrete implementation (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:352)
[2022-09-21 15:47:55,225] INFO Registered loader: PluginClassLoader{pluginLocation=file:/opt/plugins/http-connector-for-apache-kafka/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:264)

`

**Comment by ecararus** [comment]
I have just downloaded version [kafka_2.11-2.4.0.tgz](https://archive.apache.org/dist/kafka/2.4.0/kafka_2.11-2.4.0.tgz)  from.
and started with couple of other plugins (io.debezium.connector.postgresql.PostgresConnector, com.nordstrom.kafka.connect.sqs.SqsSinkConnector) and all started in the same way. 

When i listed available plugins is everything is there except "io.aiven.kafka.connect.http.HttpSinkConnector"

Did similar test using  bitnami container and in that case "io.aiven.kafka.connect.http.HttpSinkConnector" has bee loaded successful in both distributed and standalone mode here's the dockerfile 

`
FROM bitnami/kafka:2 AS fsb_connect_base
USER 1234
#ADD PLUGINS
ADD ./*.jar  /opt/bitnami/kafka/libs/

EXPOSE 8083
`

Do you think it might be related to scala version or kafka version ?

**Comment by ecararus** [comment]
The issue is cause by the java version.
The connector is not working under version 1.8 min version is 11.

Based on above consider the ticket closed.
