### ISSUE TITLE
Integration Test Run -org.testContainers.containers.ContainerFetchException 

### ISSUE THREAD

**Issue by omprak** [aiven/http-connector-for-apache-kafka#23]
I am using Intellij and Docker is running (service as docker for Mac). I am using ./gradlew integrationTest  but all tests are failing as org.testContainers.containers.ContainerFetchException 

My understanding is it's trying to run Kafka Container. But I am not sure what additional steps I have to take other than running Docker which is already running .

**Comment by willyborankin** [comment]
I faced with such problem as well. You need to pull `ryuk:0.3.0` manually `docker pull testcontainersofficial/ryuk:0.3.0` and after that execute `gradle integrationTests`.

**Comment by omprak** [comment]
I have tried and pulled ryuk :0.3.0 and executed test again but still facing same issue

**Comment by omprak** [comment]
aiven-kafka-connect-http fompraka$ docker pull testcontainersofficial/ryuk:0.3.0

0.3.0: Pulling from testcontainersofficial/ryuk

Digest: sha256:c1db2dd82bb379175034df6f9fade7e429784af815daebf6fa5e92c27395ece2

Status: Image is up to date for testcontainersofficial/ryuk:0.3.0

docker.io/testcontainersofficial/ryuk:0.3.0

aiven-kafka-connect-http fompraka$ ./gradlew integrationTest

 

> Task :integrationTest

 

AvroIntegrationTest > testBasicDelivery() FAILED

    org.testcontainers.containers.ContainerFetchException at AvroIntegrationTest.java:87

        Caused by: com.github.dockerjava.api.exception.InternalServerErrorException at AvroIntegrationTest.java:87

 

IntegrationTest > testBatching() FAILED

    org.testcontainers.containers.ContainerLaunchException at GenericContainer.java:330

        Caused by: org.testcontainers.containers.ContainerFetchException at GenericContainer.java:1279

            Caused by: com.github.dockerjava.api.exception.ConflictException at OkHttpInvocationBuilder.java:291

**Comment by bsideup** [comment]
Consider using the latest version of Testcontainers (1.15.2), there were a few major changes in Docker that are incompatible with old versions of Testcontainers, unfortunately.

**Comment by ivanyu** [comment]
Thanks for the info @bsideup. We'll surely update the library.

**Comment by bsideup** [comment]
@ivanyu feel free to ping me next time you have Testcontainers-related things. Always happy to help!

**Comment by willyborankin** [comment]
@omprak Hi test containers version upgraded.

**Comment by AnatolyPopov** [comment]
Seems this issue has been resolved. Closing it because of inactivity.
