### ISSUE TITLE
Connector doesnt send Content-Type header no matter what

### ISSUE THREAD

**Issue by dimagoldin** [aiven/http-connector-for-apache-kafka#29]
i've configured ```http.headers.content.type=application/json``` in the connector configuration and the connector sends POST requests without content-type header no matter what. 
I'm receiving HTTP status 415 from my backend due to undefined content-type.

I've checked using Wireshark and logged incoming requests in the receiving service and the "Content-Type" header is missing.

**Comment by ivanyu** [comment]
@dimagoldin thank you for this report. We've added this into our backlog and will deal with this issue.

**Comment by arcmmartins** [comment]
Hello @ivanyu,

I am also getting this issue when using authentication type that is not STATIC, It appears that the content type is only being added on the AUTH_HTTP_REQUEST_BUILDER that is used when the authentication type is STATIC.

I think the solution would be to add this on the DEFAULT_HTTP_REQUEST_BUILDER (requires confirmation also on the oauth one).
