### ISSUE TITLE
"if" statement that doesn't make sense?

### ISSUE THREAD

**Issue by lavalex** [aiven/http-connector-for-apache-kafka#35]
Hello,

In HttpResponseHandler, there is:

if (response.statusCode() >= 400) {
            if (response.statusCode() < 200 || response.statusCode() > 299) {

What is the point checking " if (response.statusCode() < 200 || response.statusCode() > 299)" ? We already know it's bigger or equal 400.

**Comment by hackaugusto** [comment]
@lavalex thanks for the report, I have opened a PR to remove the unnecessary if statement.
