### ISSUE TITLE
Release 0.5.0 request

### ISSUE THREAD

**Issue by arcmmartins** [aiven/http-connector-for-apache-kafka#43]
Hello,

Taking into account all the new commits with new features and bug fixes introduced since 0.4.0 would it be possible to generate a 0.5.0 release?

Thank you

**Comment by ivanyu** [comment]
Yeah, sure, we'll make a release

**Comment by ivanyu** [comment]
Here you go: https://github.com/aiven/http-connector-for-apache-kafka/releases/tag/v0.5.0
