### ISSUE TITLE
Downstream URL need support `POST` or `PUT`?

### ISSUE THREAD

**Issue by Hongbo-Miao** [aiven/http-connector-for-apache-kafka#45]
For [HTTP Sink Connector for Confluent Platform](https://docs.confluent.io/kafka-connect-http/current/overview.html), it says

> The String representation of each record is then put into the request body before being sent to the downstream `http.api.url` via a `POST` or `PUT` request.

I am wondering what does Aiven's HTTP Sink Connector for Apache Kafka require for the downstream URL? Is it also `POST` or `PUT`?
I didn't find the info in the [readme](https://github.com/aiven/http-connector-for-apache-kafka/blob/main/README.md) and the [docs](https://github.com/aiven/http-connector-for-apache-kafka/blob/main/docs/sink-connector-config-options.rst). It would be great to clarify in the docs.

Thanks! 😃

**Comment by ivanyu** [comment]
Hi @Hongbo-Miao 
It's POST only at the moment. I made a PR to clarify this and some other things: https://github.com/aiven/http-connector-for-apache-kafka/pull/46

**Comment by Hongbo-Miao** [comment]
Thanks @ivanyu !
