### ISSUE TITLE
Add support for non schema json object

### ISSUE THREAD

**Issue by Uriende** [aiven/http-connector-for-apache-kafka#48]
Hey guys,
Been looking to use the connector for our use case and we encoutered an issue when using it with a
JsonConverter with no schema.
https://github.com/aiven/http-connector-for-apache-kafka/blob/main/src/main/java/io/aiven/kafka/connect/http/converter/RecordValueConverter.java
only supports String or Struct but the object we got was a Hashmap. 
I'm going to see if I can sort it myself and open a pull request if I do.

**Comment by jjaakola-aiven** [comment]
@Uriende Thank you for the contribution.
