### ISSUE TITLE
Support for batches in JSON format

### ISSUE THREAD

**Issue by 1riatsila1** [aiven/http-connector-for-apache-kafka#54]
Does the connector support json output when batching.enabled = true? If not, this this would be a very useful feature.

**Comment by ivanyu** [comment]
Hi @1riatsila1 
Do I understand correctly, you mean the output to be
```json
[
  {record-1-in-json},
  {record-2-in-json},
  ...
]
```
?

**Comment by 1riatsila1** [comment]
Hello @ivanyu

Yes this is what I mean :-)

**Comment by ivanyu** [comment]
@1riatsila1 will https://github.com/aiven/http-connector-for-apache-kafka/pull/53 help?
