### ISSUE TITLE
Upgrade to Jetty to 11.0.x

### ISSUE THREAD

**Issue by jlprat** [aiven/http-connector-for-apache-kafka#73]
Jetty is now on version 11, while the project still uses version 9. However API changed in the meantime and the project doesn't compile any more.

We should upgrade the dependency and apply all needed changes at API level.

**Comment by ivanyu** [comment]
It starts looking it needs much more attention than we want to spend on this test dependency (e.g. not found `Slf4jRequestLog`, needed to start Connect worker during integration testing if updated to 10 or 11). Better keep it as is
